### ISSUE TITLE
鹿港龍山寺&openheritage3d.org

### ISSUE THREAD

**Issue by natowi** [areong/taiwan-culture-3dscan#13]
## 拍攝主體
I just wanted to point you to the [OpenHeritage](https://openheritage3d.org/) project.

鹿港龍山寺
https://openheritage3d.org/project.php?id=tnav-3t41
https://cyark.org/projects/lukang-longshan-temple/in-depth

It is important to collect not only the generated 3D model, but also the original photos, so the 3D model can be re-computed in the future.

**Comment by areong** [comment]
@natowi That's right. I do keep all photos for reconstruction but have not yet make them public. Thank you for the suggestion. I will add to guideline to ask participants share their photos.

For the Open Heritage project, I am really surprised at such ambitious project and so much contribution has already been made. One of my goal is to involve more and more people into the world of 3D preservation. Thus I started this GitHub project, and I'll keep spreading the knowledge and experience I have as much as I can.

**Comment by natowi** [comment]
I am looking forward to see how your project develops.
